### ISSUE TITLE
Suggestion regarding the YouTube Notifications

### ISSUE THREAD

**Issue by Z1ren** [Wassup789/YouTube-Notifications#1]
Hi,
i really love your chrome extension. It works great for my purposes. 
The only improvement i would really like to suggest is an extra button on the pop-up alongside  'Watch' and 'Dismiss' that would allow me to add the video to the 'watch later' queue on Youtube. 

(Don't know if there are potential problems with rights management regarding the google account that would make this difficult?)

Thanks for your great work so far

Best regards
Heiko

**Comment by Wassup789** [comment]
I have the bare bones of your requested feature completed. I just have to make some minor adjustments and add it to the settings portion of the popup menu. Thanks for your suggestion!

**Comment by Wassup789** [comment]
I have published the latest version to the Chrome web store and should be available within 24 hours.  If you have any more issues or suggestions regarding this, feel free to message me.

**Comment by Z1ren** [comment]
Just updated to 1.1.2.0  
New feature works perfectly. Thank you very much my friend :)
