### ISSUE TITLE
Integration Potplayer Youtube Shortcut

### ISSUE THREAD

**Issue by Saoromat** [Wassup789/YouTube-Notifications#11]
Hey. I use PotPlayer https://chrome.google.com/webstore/detail/potplayer-youtube-shortcu/cfdpeaefecdlkdlgdpjjllmhlnckcodp?hl=ru as the main player for video from Youtube due to poor support for playlists from youtube team. I found your app is very easy to create a playlist for PotPlayer through the right-click menu in the program. But I want to ask whether to put a more complete support like this:
![youtube](https://cloud.githubusercontent.com/assets/22244042/18598031/9403f294-7c59-11e6-8f62-8d374c4a305d.png)
There are a couple of comments on the notification window:
- very often cuts the channel name. Maybe put it in a third separate line
- is it posible to put channel logo to notification window
  ![youtube_2](https://cloud.githubusercontent.com/assets/22244042/18598653/9cf8ffea-7c5c-11e6-86d5-5c8f5dbebc65.png)
  Read previous issue and i hope you add some numbers to main program badge in future.  Later i use
  https://chrome.google.com/webstore/detail/youtube-ex/eoeljlbdbgaeocdnnepagaibkpbdnfon?hl=ru
  and it has nise cont syste for example, but it was broken by new youtube api.

**Comment by Wassup789** [comment]
Sadly Chrome's rich notifications are limited to only two buttons. I will however look into adding customization of the second notification button to add your proposed implementation to the extension.

**Comment by Saoromat** [comment]
I noticed that the [play video] button is duplicated, the video can be opened by clicking on the image. For myself, I would replace it on the add PotPlayer if there was such an option.

**Comment by Wassup789** [comment]
### Play Button Duplication Response

Yes, the the watch video button is duplicated however I do not want to replace the button with PotPlayer as PotPlayer is not directly related to the main focus of this extension nor is it a Google service that I can rely on with the fact that it is not a Google API, but a third party application. I will look into adding customizability of the notification buttons but because of my "design choices" for the extension it will not be a default feature. Hopefully, you can understand.

### Notification Layout Issue

I will look into the display issue you have encountered but I don't think I will be able to add another line as yet again, the Chrome extension API puts a lot of limitations that I cannot override.

**Comment by Saoromat** [comment]
Of course I understand, not even hoping that it will enter the main interface. I was hoping it easy to implement and make some subversion via separate file and post it here on the website under the codes. 
Maybe someone else interested in it. Well, if this is difficult, then get a little advice in which direction to move to try to do it by myself, if it's possible.
As for Notification Layout, the text itself is not so important for me, I just noticed a bug. For my visual memory is more important the image, logo of the channel. Sometimes it is confuse, especially when i turn on my computer. I get 10 or more messages, some from the same author. If this happens more quickly go to a standard subscription youtube page instead of clicking each tab in the main window of your program. 
I may seem intrusive, but I write a lot of words to better describe the problem to make your rxtention even better. Since English not my native language, I must to write a lot.

**Comment by Wassup789** [comment]
Don't worry about the complexity of the implementation or if you're being intrusive. I enjoy getting these types of features implemented or bugs fixed, therefore I will attempt to add the feature you requested.

Could you elaborate what you mean by:

> I get 10 or more messages, some from the same author. If this happens more quickly go to a standard subscription youtube page instead of clicking each tab in the main window of your program.

I'm sorta confused about what you said.

**Comment by Saoromat** [comment]
It's a complex problem.
- notification window does not have a logo like in the first picture on the first post
- in notification window the name of the channel is often сuting off like in the first picture on the first post
- the program does not mark video as new one and don't count them

I do not know what this video is, is it important and worth a look right now or wait for later. I have to go here 
![youtube_3](https://cloud.githubusercontent.com/assets/22244042/18604827/18331c26-7c8b-11e6-83b5-ffdae5a5d711.png)
to see what a channel sent the video read the full name of the video and then decide what to do. But when there are more than ten, as is often hapens after waking up computing system, now I have ten or more  unknown authors  to me. I have to check everyone, missed one video or two or more from the same author. But now you need to press the blue button  risking to get the red and unsubscribe, . In thet case i'm going to a standard YouTube page, this is faster and there is no red button.
I hope that did best in the translation and explanation.

**Comment by Wassup789** [comment]
Thank you very much for your feedback.

### Author profile photo not displaying

I just changed the icon to display the author's icon, see commit: 89521086645d19182a6c09d8dca036526efe18a1.

### Notification title cutting off

I have already fixed the author issue, see commit: fec4944121db6d34bdd96670acf00bc644eb4f2c. 

### Extension does not mark new videos

Issue #10 highlights this issue.

### Info and remove button conflict

I might make it so the remove button needs to be pressed two times as I dont want to remove the button as users may get confused about how to remove a channel. If you have a better solution to this, leave a reply.

**Comment by Saoromat** [comment]
Forgot an important thing, I do not use Chrome, i use UC browser. Extensions must be compatible but who knows.

### Info and remove button conflict

I think your idea for double click to remove the subscription is the best solution to get rid of random mistake and will not be so intrusive in removing many subscriptions as it would be if we get floating window "you really want to delete" "yes" or "no".

### Notification title cutting off

I think the best way to solve it once and for all times it's like hear
![youtube_4](https://cloud.githubusercontent.com/assets/22244042/18608165/a9625a04-7cea-11e6-86f0-868742f863d2.png)
add a pop-up text with a full description.
I also never used the "watch later" button, it seems does not work for me in the old and in the test version too.
Author profile photo works perfectly, thanks!

**Comment by Wassup789** [comment]
Commit: 01b14cdbc63449764321a3a7573a8caccc78eccf addresses the issue with the two buttons being too close to each other.
![http://i.imgur.com/kgy5DLT.gifv](http://i.imgur.com/kgy5DLT.gif)

**Comment by Wassup789** [comment]
My latest commit, fdf891c84b1ae572d2d548f7c55ebeefd253f927 adds custom notification support and the PotPlayer integration you have requested. This is not final, as currently it opens a new Chrome window/tab to open up PotPlayer.

**Comment by Saoromat** [comment]
What am I doing wrong during installation? In master branch missing (settings.html, bower_components, settings.js). I try them from the 1.2.0 version but they obviously not the same  that are needed.

**Comment by Wassup789** [comment]
Read the INSTALL.md. You should have bower and npm installed.

**Comment by Classy-Cube** [comment]
Posting to say I love the Pot Player integration, without it I couldn't get links to open in Pot Player.  Like @Saoromat I use the "PotPlayer YouTube Shortcut" and while it looks like the context menu options should work they don't. Neither option to use the middle mouse button. Instead, it opens them in a background tab. 
![4e0826bd-cccb-4c3b-9ce0-6004b5140937](https://user-images.githubusercontent.com/13388890/32396447-a28319a6-c0bb-11e7-890f-cf0120352e74.GIF)
Thanks, @Saoromat for posting and @Wassup789 the development.

**Comment by Saoromat** [comment]
As I have noticed, this bug appears rarely, basically the first time you start the browser. Sometimes even disappears ADD link from menu. For treatment, I just open the movie and add it from the Youtube page.
Then everything works fine. That's all I can say about this.

![default](https://user-images.githubusercontent.com/22244042/32398033-55a1861a-c0f5-11e7-87dc-c2d9137c75d8.png)

**Comment by Wassup789** [comment]
A possible reason why that extension might not work is because of how Chrome deals with URLs within extension popups.  Clicking on an link in the popup will not open the link and the only way to circumvent this was for the extension to manually create a tab with the URL.

Using the context menu or the middle mouse button however, opens the URL as intended without the use of additional code.

Code example:
```javascript
$(document).on("click", "a", function(){// Listens for when a user clicks on a link
    chrome.tabs.create({url: $(this).attr("href")});// Manually create a tab with the url
});
```
