### ISSUE TITLE
uploading sound doesn't work

### ISSUE THREAD

**Issue by tjw0lf** [Wassup789/YouTube-Notifications#13]
How to upload sound its not working when i pick sound effect nothing goes in. Is there a way to place it in manually....Please Help

**Comment by Wassup789** [comment]
Is it possible to attach the audio file you're attempting to upload?

**Comment by tjw0lf** [comment]
Here you go, 
no mp3.s We don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

https://www.dropbox.com/s/44n1x6prkyfsgmq/annoying-arcade-loop.mp3?dl=0

**Comment by Wassup789** [comment]
Alright, I'll look into the issue later, don't have access to my project at thee moment.

**Comment by Wassup789** [comment]
Hmm, the audio file works completely fine for me. Have you expanded the dropdown menu and selected your audio file?

**Comment by tjw0lf** [comment]
I clicked the "upload sound" then went to where its saved in Download folder and clicked the mp3. I hit the drop down but nothing there just default. How did you get it to work

**Comment by Wassup789** [comment]
I tried this on both the production build and unstable build and they both seem to work completely fine. Can you right click on the popup, click on "Inspect", then press the Console Tab and try uploading with the window open. If any errors occur, please paste a copy of that error log.

**Comment by tjw0lf** [comment]
where is Inspect

**Comment by Wassup789** [comment]
https://puu.sh/rp6N5/7a6642d710.mp4

**Comment by tjw0lf** [comment]
That's the problem. When i hit "upload sound" and file manger comes up the youtube notifer closees right away so when i click the mp3 its not opend to put it in. When i hit inspect and did it it worked

**Comment by Wassup789** [comment]
Alright, I see. Could you provide me information about your computer? All I require is your operating system and version of chrome located at chrome://help

**Comment by tjw0lf** [comment]
I'm using Linux Gnome openSUSE tumbleweed. Chrome version 53.0.2785.116 (64-bit)

**Comment by Wassup789** [comment]
Alright, so I have tested this in my Ubuntu VM and I encounter the same issue you are having. Apparently, this issue was fixed for Mac OS X a couple years ago but still occurs in GNOME AFAIK, haven't tested any other OSes. I will look into a workaround for this issue, but for now you would have to use the inspect tool to circumvent this.

I have also sent this issue to the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=650536) in hopes that this will be fixed soon.

**Comment by tjw0lf** [comment]
OK Thank you very much for your hard work this is a great add on for chrome. Youtube i use it all day every day and glad somebody made nice add on its handy. I have a lot of subs on youtube and watch a lot of video on Linux and stuff i do my own and its awesome to keep up with everyone. 

At least you know of the problem and will be working on it to get fixed. Thank you

Let me know where that donate button is #Wassup789 and when i get some cash i will donate

**Comment by Wassup789** [comment]
Thank you very much, I appreciate your kind words. I have created a temporary fix for the issue you've encountered until that bug gets resolved. This fix will be live once I publish the next version for this extension.
