### ISSUE TITLE
Addon stop work

### ISSUE THREAD

**Issue by artnurr** [Wassup789/YouTube-Notifications#18]
Already a few days channel updates does not work

**Comment by Wassup789** [comment]
It appears the YouTube Data API does not return the statistics (likes, dislikes, view count, video duration) for some channels for some reason which breaks the updating. I'll see what I can do to circumvent this.

**Comment by Wassup789** [comment]
Commit 130b775da7591d4ee2b010606590a514a49d8eca resolves this issue. Look out for an update in a few hours.

Note: Video statistics will show up as NaN until I can fix this within my control because at the moment I cannot do anything about this until YouTube fixes this.

**Comment by artnurr** [comment]
Thanks. Waiting for addon update.

**Comment by artnurr** [comment]
Addon stop work again

**Comment by Wassup789** [comment]
Could you provide some channels that are affected to recreate the bug? I have no issues with mine.
