### ISSUE TITLE
addon for firefox

### ISSUE THREAD

**Issue by Joseph65** [Wassup789/YouTube-Notifications#20]
Are you planning to release a version for firefox
I currently open a youtube link with the addon "openwith" [https://addons.mozilla.org/es/firefox/addon/open-with](url) and open the link with mpv, it would be nice to have it available for firefox.

**Comment by Wassup789** [comment]
The extension uses a some Chrome APIs and the styling was built and tested for Chrome as well.  I cannot guarantee that there will be a Firefox port. Sorry.
