### ISSUE TITLE
Doesn't show the "Add to Youtube Notfications" button on the New Youtube Layout

### ISSUE THREAD

**Issue by ranykamel** [Wassup789/YouTube-Notifications#22]
I'm missing the "Add to Youtube Notifications" button on the New Youtube Beta Layout.
I'm wondering if you'd add support for the new layout?

Here's an image of where it should've been: 
![sfdf](https://user-images.githubusercontent.com/25268334/28727838-8fc12994-73c6-11e7-8e64-538afbfd0d2b.png)

Thanks

**Comment by Wassup789** [comment]
Apologies for the late reply, the new version which has been pushed just now will work with the new layout.
