### ISSUE TITLE
Extension Notifies even when setting is off

### ISSUE THREAD

**Issue by dapsych0** [Wassup789/YouTube-Notifications#23]
I have, for one reason or another, disabled notifications  but they still come through.

I've looked through the code and cannot see anywhere that the option of 'settings.notifications.enabled' is checked when calling to notify. It only checks for this setting when adding default options.

I've cloned this, so will probably fix on my branch if this isn't done soon - and will PR if I do it first :)

**Comment by Wassup789** [comment]
It appears that I forgot to implement it when I refactored my code. This is fixed in commit 2ae94de6846351f9362d017444bc59637837bb60.

**Comment by dapsych0** [comment]
Thanks :)
