### ISSUE TITLE
"Add to YTN" buttons add wrong channel, adds Vox

### ISSUE THREAD

**Issue by Classy-Cube** [Wassup789/YouTube-Notifications#26]
![failing-pile-of-garbage](https://user-images.githubusercontent.com/13388890/32386909-2474adee-c099-11e7-860b-d1847cd5128e.GIF)
Currently, the "IMPORT SUBSCRIPTIONS" button misses many of my subscriptions so I tried manually allowing channels but I ran into this issue.
Pages used: https://www.youtube.com/feed/channels https://www.youtube.com/channel/UC2q7qe9YgHFIRP8W18yI1MA 
"Add to YouTube Notifications" buttons did nothing.
https://www.youtube.com/subscription_manager 
Google Chrome Version 62.0.3202.75 (Official Build) (64-bit) 
Only extension enabled is YouTube Notifications.
Gifs created using Snagit.

**Comment by Wassup789** [comment]
This is actually a known bug, due to the fact that YouTube decides to store Vox's channel ID for all of the subscribe buttons for some odd reason. I have found some ways to circumvent this but haven't been able to allocate time due to other projects and such. I'll see what I can do.

**Comment by Classy-Cube** [comment]
That is so strange, especially considering Vox is a relatively new channel.(Created in 2014 ~~by Buzzfeed~~)
Thanks for working on this, I love the overall look and I think it could be a very popular extension.

**Comment by Wassup789** [comment]
Yeah, its an odd issue. I've actually thought this was a personal issue as I actually have Vox subscribed but its useful to know that this is not in fact that type of issue.

(BTW, Vox is actually not created by Buzzfeed, owned by Vox Media)

**Comment by Classy-Cube** [comment]
Sorry for the bad information, could have sworn that's how they started.

**Comment by Wassup789** [comment]
This bug is resolved in commit: 1735e1b960c5cbe86cf95de49de543b76b83f9a8. Just need to do some testing to be certain that it'll work for all the buttons.
