### ISSUE TITLE
Two 'Add to YouTube Notifications' buttons in old YouTube format

### ISSUE THREAD

**Issue by Classy-Cube** [Wassup789/YouTube-Notifications#27]
![add_to_youtube_notifications](https://user-images.githubusercontent.com/13388890/32978280-ee176802-cc0c-11e7-8a6f-880427c2533e.png)

**Comment by Wassup789** [comment]
Any reason why this is closed?

**Comment by Classy-Cube** [comment]
Closed thread since focus should be on the new design and many features are broken with the older design.

**Comment by Classy-Cube** [comment]
I know it must look pretty silly, opening then closing the thread. Just realized supporting the old design doesn’t make a ton of sense.

**Comment by Wassup789** [comment]
Agreed. However, I never knew you could view the legacy layout so I never really bothered with the old layout. I just fixed this in commit 502b4c9dcdc2e5c7e82c608f0091b419287525d2, :stuck_out_tongue_closed_eyes:.

**Comment by Classy-Cube** [comment]
Haha, thanks, I still use it out of familiarity but the new design looks good. I don’t think I’ll have a problem making the jump to use your extension. Some other things don’t work with the old design but I doubt YouTube will support it much longer anyway. The issues are with https://www.youtube.com/subscription_manager where buttons don’t work and https://www.youtube.com/feed/channels where there is a lack of buttons.

**Comment by Classy-Cube** [comment]
I didn’t want to create a thread about this but what does “Synchronize with YouTube” do?
![2017-11-18_3-34-32](https://user-images.githubusercontent.com/13388890/32978511-7e75983e-cc11-11e7-9fcb-878b52e72c4e.png)

**Comment by Wassup789** [comment]
It syncs the extension with the channels you've turned on notifications with (the bell next to the channel name).

**Comment by Classy-Cube** [comment]
Interesting, did I do something wrong here?
![f9f4ee1f-a946-4087-9536-18bb169a7730](https://user-images.githubusercontent.com/13388890/32978529-ed5c1cfa-cc11-11e7-989e-b5ff8c27fea6.GIF)

**Comment by Wassup789** [comment]
You will need to refresh the page.

**Comment by Classy-Cube** [comment]
🤦‍♂️ Well, I didn’t have Synchronize with YouTube enabled but I still think I’m having an issue.

**Comment by Classy-Cube** [comment]
Surely I’m missing something. I’m using the new YouTube design and refreshed before and after clicking the bell so the extension will work.
![f11c5ba4-2530-4dc0-a526-914bad7a26c7](https://user-images.githubusercontent.com/13388890/32978602-7ef16f98-cc13-11e7-8de9-635d9a9e9855.GIF)

**Comment by Wassup789** [comment]
Yeah, sorry about that. Appears that YouTube changed how that button works. A commit and update will be out in a few hours.

**Comment by Classy-Cube** [comment]
Closing and re-opening chrome has made the channel show up in the extension.

**Comment by Classy-Cube** [comment]
Just going to test it out again.

**Comment by Classy-Cube** [comment]
Exact same thing happened.
1. Click the get notifications button on channel page
2. Close Chrome
3. Re-open Chrome open channel page 
4. Pop-up from the channel and channel in extension.

**Comment by Classy-Cube** [comment]
I like that you found a way to consolidate the bell button and “Add to YTN” but I’m concerned users reading “Synchronize with YouTube” may think it refers to only being subscribed to channels. Perhaps you should rename “Synchronize with YouTube”?

**Comment by Wassup789** [comment]
Synchronize with Youtube's bell would sort of work, anything you have in mind?

**Comment by Classy-Cube** [comment]
Sounds great to me.

**Comment by Classy-Cube** [comment]
“Synchronize with channel bell” might be better but I’m not ecstatic about either.

**Comment by Classy-Cube** [comment]
Also to nitpick don’t you think this would be better:
“Add buttons on YouTube:”
Instead of:
“Enable add buttons on YouTube:”
All other options lack the enable before the description of what they do.

**Comment by Wassup789** [comment]
I've fixed this issue in commit 587ac6e531e008ad22428fc6c71bf636f744fd03. An update has been pushed to the Chrome web store and should be available in the next few hours.

**Comment by Classy-Cube** [comment]
Fantastic, thanks for working on this extension I think it fulfills a great role. I particularly like the ability to get notifications for playlists. For channels, I don’t want to subscribe to but follow a playlist from it solves elegantly.

**Comment by Wassup789** [comment]
Yeah that's a better name for sure.  I'll get that replaced in a later commit.

**Comment by Wassup789** [comment]
Thanks that means a lot. Be aware though, the synchronization with the bell will remove any channels/playlists that do not use the bell. Probably best to not use that feature if you plan on adding playlists.

**Comment by Classy-Cube** [comment]
Okay, thanks for the heads up. 😊
