### ISSUE TITLE
importar assinaturas não está funcionado

### ISSUE THREAD

**Issue by MauricioCastioni** [Wassup789/YouTube-Notifications#36]
importar assinaturas não está funcionado antes era só marcar o sino e automaticamente começava a notificar acho que o youtube modificou algo no código do sino. Estou tendo que fazer manualmente cada canal adicionando o nome.

**Comment by MauricioCastioni** [comment]
Hi . Synchronize with YouTube's bell problem

**Comment by Wassup789** [comment]
Updated in recent commit 289eb71. Update information unknown for now.

For more info: https://github.com/Wassup789/YouTube-Notifications/issues/39#issuecomment-609480557
