### ISSUE TITLE
The settings window looks silly in french

### ISSUE THREAD

**Issue by Pizzacus** [Wassup789/YouTube-Notifications#5]
![](https://i.imgur.com/maZp4SP.png)

(The volume section)

I might fix it myself, I just wanted to let you know because I have no idea about what could be done at the moment

**Comment by Pizzacus** [comment]
Maybe if we had the volume slider under the notification switch, it would leave much more place for the test button

**Comment by Wassup789** [comment]
That would work but the switch would have too much white space.

**Comment by Pizzacus** [comment]
![](https://i.imgur.com/ADP69Op.png)

We could fill this white-space by making the test button bigger, but maybe it'll look weird, because it would be too big

(Note: On this image, I know the button isn't bigger, I just want to be sure that I'm clear on what I'm suggesting)

**Comment by Pizzacus** [comment]
It could also just be a little bigger and be centred vertically and horizontally in the space left

**Comment by Wassup789** [comment]
The white-space I'm concerned about is the notification on/off switch.

**Comment by Wassup789** [comment]
![2016-08-16_16-14-37](https://cloud.githubusercontent.com/assets/1007707/17719049/97d242a4-63cc-11e6-8619-2c5da9967533.png)
Changed the letter-spacing to -0.5px, removed padding and the volume slider width to 90px. I think this works best. Looking into the import subscriptions button row now.

**Comment by Pizzacus** [comment]
Maybe yes, I think would be the best, as far as I can tell

**Comment by Pizzacus** [comment]
I think this issue is the only issue of this kind (presentation problems when using the french version)

**Comment by Wassup789** [comment]
Alright, that's great. Thank you.
